merchants:
  - name: "The Wanderer"
    items:
      - item: "minecraft:ender_pearl"
        price: 10
        amount: 1
      - item: "minecraft:shulker_box"
        price: 10
        amount: 1
      - item: "minecraft:dragon_breath"
        price: 10
        amount: 1
      - item: "minecraft:spider_eye"
        price: 10
        amount: 1
      - item: "minecraft:blaze_rod"
        price: 10
        amount: 1
      - item: "minecraft:experience_bottle"
        price: 10
        amount: 1
      - item: "minecraft:ghast_tear"
        price: 10
        amount: 1
  - name: "The Druid"
    items:
      - item: "minecraft:carrot"
        price: 10
        amount: 1
      - item: "minecraft:oak_sapling"
        price: 10
        amount: 1
      - item: "minecraft:spruce_sapling"
        price: 10
        amount: 1
      - item: "minecraft:birch_sapling"
        price: 10
        amount: 1
      - item: "minecraft:jungle_sapling"
        price: 10
        amount: 1
      - item: "minecraft:acacia_sapling"
        price: 10
        amount: 1
      - item: "minecraft:dark_oak_sapling"
        price: 10
        amount: 1
      - item: "minecraft:mangrove_propagule"
        price: 10
        amount: 1
      - item: "minecraft:slime_ball"
        price: 10
        amount: 1
      - item: "minecraft:brown_mushroom"
        price: 10
        amount: 1
      - item: "minecraft:red_mushroom"
        price: 10
        amount: 1
      - item: "minecraft:scute"
        price: 10
        amount: 1
      - item: "minecraft:string"
        price: 10
        amount: 1
  - name: "The Hunter"
    items:
      - item: "minecraft:leather"
        price: 10
        amount: 1
      - item: "minecraft:feather"
        price: 10
        amount: 1
      - item: "minecraft:gunpowder"
        price: 10
        amount: 1
      - item: "minecraft:arrow"
        price: 10
        amount: 1
      - item: "minecraft:rabbit_stew"
        price: 10
        amount: 1
locations:
  - name: "Ruin 1"
    world: "world"
    x: 42
    y: 80
    z: -3
  - name: "Ruin 2"
    world: "world"
    x: 24
    y: 79
    z: 3
  - name: "Ruin 3"
    world: "world"
    x: 47
    y: 79
    z: 6