merchants:
  - name: "The Wanderer"
  - name: "The Druid"
  - name: "The Hunter"
locations:
  - name: "Ruin 1"
    world: "world"
    x: 42
    y: 80
    z: -3
  - name: "Ruin 2"
    world: "world"
    x: 24
    y: 79
    z: 3
  - name: "Ruin 3"
    world: "world"
    x: 47
    y: 79
    z: 6