name: WanderingMerchants
author: Arcamere
version: '${version}'
main: com.arcamere.wanderingmerchants.WanderingMerchants
api-version: '1.20'
depend:
  - kotlin-stdlib
  - PlayerNPC
  - Vault
commands:
  wanderingmerchants:
    description: Wandering Merchants command
    usage: /<command>